---
title: "Contents"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

- [Preprocessing](0-preprocessing.html):
    - Calculation of QC metrics & identification of outliers using `scater`
    - Filtering of genes and cells
    
- [Clustering](1-clustering.html):
    - Integration & clustering using a sequence of resolutions
    - t-SNE and UMAP dimension reductions colored by sample, group, and cluster ID
    
- [Annotation](2-annotation.html):
    - Number of clusters by resolution
    - Number of cells by cluster-sample
    - Relative cluster abundances by sample
    - t-SNE colored by expression of known marker genes
    - Heatmap of mean known marker-gene expressions by cluster
    - Identification of cluster-markers using `scran`
    - Hetamap of mean `scran` marker-gene expressions by cluster
    
- [DS analysis](3-differential.html)
    - Cluster annoation
    - Aggregation to pseudobulk counts
    - Pseudobulk-level MDS plot
    - Cluster-level DE analysis with `edgeR`
    - Results filtering & overview
    - Dimension reduction: t-SNE & UMAP

- [Visualization](4-visualization.html)
    - Cluster-sample cell counts
    - Cell-level vis.: Violin plots
    - Sample-level vis.: Heatmap of cluster-sample mean-expressions
    
- [GSEA](5-geneset.html)
    - Cluster-level GSEA using `camera`
    - Heatmap summary
    - Barcode plots
