suppressMessages({
    library(AnnotationDbi),
    library(circlize),
    library(countsimQC),
    library(cowplot),
    library(data.table),
    library(DESeq2),
    library(DropletUtils),
    library(dplyr),
    library(edgeR),
    library(ggplot2),
    library(ggrastr),
    library(iCOBRA),
    library(kSamples),
    library(jsonlite),
    library(limma),
    library(M3C),
    library(magrittr),
    library(MAST),
    library(Matrix),
    library(msigdbr),
    library(muscat),
    library(org.Mm.eg.db),
    library(pheatmap),
    library(purrr),
    library(RColorBrewer),
    library(readxl),
    library(reshape2),
    library(S4Vectors),
    library(scater),
    library(scDD),
    library(scds),
    library(scran),
    library(sctransform),
    library(Seurat),
    library(SingleCellExperiment),
    library(topGO),
    library(UpSetR),
    library(viridis),
    library(workflowr),
    library(yaml)
})
writeLines(capture.output(sessionInfo(args$txt)))

# install.packages(c("BiocManager", "devtools"))
# devtools::install_github('VPetukhov/ggrastr')
# BiocManager::install(c(
#     "AnnotationDbi","circlize","countsimQC","cowplot","data.table","DESeq2",
#     "DropletUtils","dplyr","edgeR","ggplot2","ggrastr","iCOBRA","kSamples",
#     "jsonlite","limma","M3C","magrittr","MAST","Matrix","muscat","msigdbr",
#     "org.Mm.eg.db","pheatmap","purrr","RColorBrewer","readxl","reshape2",
#     "S4Vectors","scater","scDD","scds","scran","sctransform","Seurat",
#     "SingleCellExperiment","topGO","UpSetR","viridis","workflowr","yaml"))