---
title: "Cluster annotation"
author: 
- name: Pierre-Luc Germain
  affiliation:
  - &IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
- name: Helena L. Crowell
  affiliation: 
  - *IMLS
  - Swiss Institute of Bioinformatics (SIB), University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: true
    code_folding: hide
---

### Load packages
```{r load-libs, message = FALSE, warning = FALSE}
library(ComplexHeatmap)
library(cowplot)
library(ggplot2)
library(dplyr)
library(purrr)
library(RColorBrewer)
library(viridis)
library(scran)
library(Seurat)
library(SingleCellExperiment)
```

# Load data & convert to SCE
```{r load-data}
so <- readRDS(file.path("output", "MAGL-SeuratObject.rds"))
sce <- as.SingleCellExperiment(so, assay = "RNA")
colData(sce) <- as.data.frame(colData(sce)) %>% 
    mutate_if(is.character, as.factor) %>% 
    DataFrame(row.names = colnames(sce))
```

# Nb. of clusters by resolution
```{r}
cluster_cols <- grep("res.[0-9]", colnames(colData(sce)), value = TRUE)
sapply(colData(sce)[cluster_cols], nlevels)
```

# Cluster-sample counts
```{r}
# set cluster IDs to resolution 0.2 clustering
so <- SetIdent(so, value = "integrated_snn_res.0.1")

so@meta.data$cluster_id <- Idents(so)
sce$cluster_id <- Idents(so)
(n_cells <- table(sce$cluster_id, sce$sample_id))
```

```{r}
nk <- length(kids <- set_names(levels(sce$cluster_id)))
ns <- length(sids <- set_names(levels(sce$sample_id)))
ng <- length(gids <- set_names(levels(sce$group_id)))

# color palettes for cluster, sample, group IDs, and # cells
pal <- CATALYST:::.cluster_cols
cluster_id_pal <- set_names(pal[seq_len(nk)], kids)
sample_id_pal <- set_names(pal[seq_len(ns) + nk], sids)
group_id_pal <- set_names(c("royalblue", "orange"), gids)
```

# Relative cluster-abundances
```{r fig.width = 6, fig.height = 5}
fqs <- prop.table(n_cells, margin = 2)
mat <- as.matrix(unclass(fqs))
Heatmap(mat,
    col = rev(brewer.pal(11, "RdGy")[-6]),
    name = "Frequency",
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    row_names_side = "left",
    row_title = "cluster_id",
    column_title = "sample_id",
    column_title_side = "bottom",
    rect_gp = gpar(col = "white"),
    cell_fun = function(i, j, x, y, width, height, fill)
        grid.text(round(mat[j, i] * 100, 2), x = x, y = y, 
            gp = gpar(col = "white", fontsize = 8)))
```

# DR colored by cluster ID {.tabset}
```{r dim-red, results = "asis", fig.width = 12}
cs <- sample(colnames(so), 5e3)
.plot_dr <- function(so, dr, id)
    DimPlot(so, cells = cs, group.by = id, reduction = dr, pt.size = 0.4) +
        scale_color_manual(id, values = get(paste0(id, "_pal"))) + 
        guides(col = guide_legend(nrow = 10, 
            override.aes = list(size = 3, alpha = 1))) +
        theme_void() + theme(aspect.ratio = 1)

ids <- c("cluster_id", "group_id", "sample_id")
for (id in ids) {
    cat("## ", id, "\n")
    p1 <- .plot_dr(so, "tsne", id)
    lgd <- get_legend(p1)
    p1 <- p1 + theme(legend.position = "none")
    p2 <- .plot_dr(so, "umap", id) + theme(legend.position = "none")
    ps <- plot_grid(plotlist = list(p1, p2), nrow = 1)
    p <- plot_grid(ps, lgd, nrow = 1, rel_widths = c(1, 0.2))
    print(p)
    cat("\n\n")
}
```

# Known marker genes
```{r}
known_markers <- list(
    astrocytes = c("Aqp4", "Gfap", "Fgfr3"),
    endothelial = c("Cldn5","Nostrin"),
    microglia = c("C1qb","Tyrobp"),
    neuronal = c("Snap25", "Stmn2"),
    neuronal_excitatory = "Slc17a7",
    neuronal_inhibitory = "Gad1",
    oligodendrocyte = "Opalin",
    OPC = "Pdgfra")

known_markers <- lapply(known_markers, sapply, function(g) 
    grep(paste0(g, "$"), rownames(sce), value = TRUE))

gs <- gsub(".*\\.", "", unlist(known_markers))
ks <- rep.int(names(known_markers), vapply(known_markers, length, numeric(1)))
labs <- sprintf("%s(%s)", gs, ks)
```

## Heatmap of mean marker-exprs. by cluster
```{r fig.width = 8, fig.height = 4}
# split cells by cluster
cs_by_k <- split(colnames(sce), sce$cluster_id)

# compute cluster-marker means
means_by_cluster <- lapply(known_markers, function(gs)
    vapply(cs_by_k, function(i)
        Matrix::rowMeans(logcounts(sce)[gs, i, drop = FALSE]), 
        numeric(length(gs))))

# prep. for plotting & scale b/w 0 and 1
mat <- do.call("rbind", means_by_cluster)
mat <- muscat:::.scale(mat)
rownames(mat) <- gs

cols <- muscat:::.cluster_colors[seq_along(known_markers)]
cols <- setNames(cols, names(known_markers))
row_anno <- rowAnnotation(
    df = data.frame(label = ks),
    col = list(label = cols),
    gp = gpar(col = "white")) 
Heatmap(mat,
    name = "scaled avg.\nexpression",
    col = viridis(10),
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    row_names_side = "left",
    column_title = "cluster_id",
    column_title_side = "bottom",
    rect_gp = gpar(col = "white"),
    left_annotation = row_anno)
```

## DR colored by marker expr.
```{r fig.width = 12, fig.height = 12}
# downsample to 2000 cells
cs <- sample(colnames(sce), 2e3)
gs <- unlist(known_markers)
sub <- subset(so, cells = cs)

# t-SNE colored by marker-expression
ps <- lapply(seq_along(gs), function(i) {
    if (!gs[i] %in% rownames(so)) return(NULL)
    FeaturePlot(sub, features = gs[i], reduction = "umap", pt.size = 0.4) +
        ggtitle(labs[i]) + theme_void() + theme(aspect.ratio = 1, legend.position = "none")
})
ps <- ps[!sapply(ps, is.null)]

# arrange plots
plot_grid(plotlist = ps, ncol = 4, label_size = 10)
```

# Find markers using `scran`
```{r}
scran_markers <- findMarkers(sce, 
    clusters = sce$cluster_id, block = sce$sample_id, 
    direction = "up", lfc = 2, full.stats = TRUE)
```

## Heatmap of mean marker-exprs. by cluster
```{r fig.width = 12, fig.height = 6}
gs <- lapply(scran_markers, function(u) rownames(u)[u$Top == 1])
sapply(gs, length)
muscat::plotMarkerGenes(sce, gs)
```

# Save SCE to .rds
```{r}
saveRDS(sce, file.path("output", "MAGL-SCE.rds"))
```
